export const BoardActionTypes = {
  ON_MOVE: "ON_MOVE",
  ON_NEW_GAME: "ON_NEW_GAME",
  CREAT_GAME_START: "CREAT_GAME_START",
  CREAT_GAME_SUCCESS: "CREAT_GAME_SUCCESS",
  CREAT_GAME_FAILURE: "CREAT_GAME_FAILURE",
  UPDATE_GAME_START: "UPDATE_GAME_START",
  UPDATE_GAME_SUCCESS: "UPDATE_GAME_SUCCESS",
  UPDATE_GAME_FAILURE: "UPDATE_GAME_FAILURE",
};
